// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API127.Models;
using API127.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ERP.Infrastructure.Persistence.Configurations.ERP
{
    public partial class VillaConfiguration : IEntityTypeConfiguration<Villa>
    {
        public void Configure(EntityTypeBuilder<Villa> entity)
        {

            entity.HasMany(e => e.villaNumber).WithOne(y => y.Villa).HasForeignKey(x=>x.VillaID);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Villa> entity);
    }
}
